version: '3'

services:
  travelling-companion:
    build: .
    command: python TravellingCompanion/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db-service
  db-service:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "Travelling Companion"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: