# Generated by Django 4.0.1 on 2022-01-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravellingCompanionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('associates', models.CharField(max_length=100)),
                ('trip_date', models.DateField(verbose_name='Trip date')),
                ('total_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CitiesForTrips',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingCompanionApp.city')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TravellingCompanionApp.trip')),
            ],
        ),
    ]
