# Generated by Django 4.0.1 on 2022-01-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TravellingCompanionApp', '0002_city_trip_citiesfortrips'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='TravellingCompanionApp.user'),
            preserve_default=False,
        ),
    ]
