# Generated by Django 4.0.1 on 2022-01-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravellingCompanionApp', '0003_trip_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='user_id',
            new_name='user',
        ),
    ]
